import './globals.css'
import type { Metadata } from 'next'
import Providers from '@/components/Providers'
import StructuredData from '@/components/StructuredData'

export const metadata: Metadata = {
  // Basic metadata
  title: {
    default: 'Dharma Path | Finally Understand Hinduism',
    template: '%s | Dharma Path', // For page-specific titles like "Bhagavad Gita | Dharma Path"
  },
  description: 'A structured learning path for beginners to understand Hinduism. 110 lessons covering the Bhagavad Gita, Upanishads, Vedas, and Hindu philosophy.',
  keywords: ['Hinduism', 'Bhagavad Gita', 'learn hinduism', 'dharma', 'karma', 'spiritual learning', 'Upanishads', 'Vedas', 'Hindu philosophy', 'Sanskrit', 'meditation'],

  // Canonical URL - tells Google this is the "official" version
  metadataBase: new URL('https://mydharmapath.com'),

  // PWA
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Dharma Path',
  },

  // Open Graph - for Facebook, LinkedIn, WhatsApp, iMessage previews
  openGraph: {
    title: 'Dharma Path | Finally Understand Hinduism',
    description: 'The starting point you never had. 110 lessons covering Hindu philosophy, the Bhagavad Gita, Upanishads, and Vedas.',
    type: 'website',
    url: 'https://mydharmapath.com',
    siteName: 'Dharma Path',
    locale: 'en_US',
    images: [
      {
        url: '/opengraph-image', // Dynamically generated by opengraph-image.tsx
        width: 1200,
        height: 630,
        alt: 'Dharma Path - Finally Understand Hinduism',
      },
    ],
  },

  // Twitter Card - for Twitter/X previews
  twitter: {
    card: 'summary_large_image', // Shows a large image preview
    title: 'Dharma Path | Finally Understand Hinduism',
    description: 'The starting point you never had. Learn Hinduism step by step with 110 structured lessons.',
    images: ['/opengraph-image'],
    creator: '@dharmapath', // Update if you have a Twitter handle
  },

  // Additional SEO
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },

  // Verification (add these when you set up Search Console)
  // verification: {
  //   google: 'your-google-verification-code',
  // },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Favicon and PWA Icons */}
        <link rel="icon" type="image/png" href="/favicon.png" />
        <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />

        {/* PWA Theme Colors */}
        <meta name="theme-color" content="#F97316" media="(prefers-color-scheme: light)" />
        <meta name="theme-color" content="#1F2937" media="(prefers-color-scheme: dark)" />

        {/* iOS PWA Settings */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Dharma Path" />

        {/* Microsoft PWA Settings */}
        <meta name="msapplication-TileColor" content="#F97316" />
        <meta name="msapplication-TileImage" content="/icons/icon-144x144.png" />
        {/* Prevent flash of wrong theme */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const stored = localStorage.getItem('dharma_path_theme');
                const theme = stored || 'system';
                const isDark = theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
                if (isDark) document.documentElement.classList.add('dark');
              })();
            `,
          }}
        />
        {/* Register Service Worker for offline support */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                  navigator.serviceWorker.register('/sw.js')
                    .then(function(registration) {
                      console.log('[SW] Registered:', registration.scope);
                    })
                    .catch(function(error) {
                      console.log('[SW] Registration failed:', error);
                    });
                });
              }
            `,
          }}
        />

        {/* JSON-LD Structured Data for SEO */}
        <StructuredData />
      </head>
      <body className="min-h-screen bg-cream-100 dark:bg-gray-900 bg-sacred-pattern transition-colors duration-300">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
